### ISSUE TITLE
shalla_pihole.sh places shallalist.blacklist in the wrong location

### ISSUE THREAD

**Issue by ashisa** [mglinux/IPF_Tools#1]
shalla_pihole.sh places the shallalist.blacklist in /var/www on rpi running pi-hole. However, since the document root is set to /var/www/html, pi-hole cannot download the list properly to be used as blacklists.

System information:
Linux raspberrypi 4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux

Pi-hole:
Pi-hole Version v3.3.1 Web Interface Version v3.3 FTL Version v3.0 

I got it working by changing the path to /var/www/html from /var/www in the script.

**Comment by mglinux** [comment]
Tried this a while ago. don't know if something was changed from pi holes side. If HTML is set as root standard I will change the script tomorrow

**Comment by mglinux** [comment]
Added var for pihole_wwwroot. Could you please try the altered script? Right now I don´t have much time and no Pihole VM running :(

**Comment by mglinux** [comment]
Will install pihole in a VM again and test myself. shouldn't be much effort to adjust the script.
